### PR TITLE
add .travis.yml file for Travis CI

### PR DESCRIPTION
**Pull request by NicoleCarpenter**

### CODE REVIEW

**Comment by mnewsome** [comment]
squash

**Comment by mnewsome** [comment]
also don't see an updated README

**Comment by mnewsome** [comment]
:+1:

**Comment by zdavy** [comment]
This is doing nothing with swift package manager and it's certainly not running your tests. What value is being added here?

**Comment by NicoleCarpenter** [comment]
I think this is ready @zacharyjdavy

**Comment by NicoleCarpenter** [comment]
@mnewsome @zacharyjdavy This works

**Comment by zdavy** [comment]
:+1: if it passes

**Pull request merged**
